version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secrets
      POSTGRES_USER: secrets
      POSTGRES_DB: secretsdb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
# nota para correr esto debes ejecutar  docker-compose --compatibility up -d
